### ISSUE TITLE
Fig 1: Comparison of Chi2 Result PDFs

### ISSUE THREAD

**Issue by lgrigoli** [bmd/text-stats#1]
A graph of two probability curves: the curve generated from the comparison of two texts of the same author, and the curve generated from the two texts of different authors.

**Comment by bmd** [comment]
@lgrigoli to review

![screen shot 2015-01-11 at 10 18 52 pm](https://cloud.githubusercontent.com/assets/1526204/5698640/d985c59e-99df-11e4-9817-83b9e4dbceea.png)
