### ISSUE TITLE
Graph nos. 2-7

### ISSUE THREAD

**Issue by lgrigoli** [bmd/text-stats#3]
A graph of two probability curves: the curve derived from the initial comparisons of texts by the same author, and the curve generate from two parts of the Passio Praeiecti. 

Six iterations of this graph are needed: P1 v. P2, P1 v. P3, P2 v. P1, P3 v. P1, P3 v. P2.

**Comment by bmd** [comment]
@lgrigoli - still needed?

**Comment by bmd** [comment]
Done
